blank_issues_enabled: false
contact_links:
  - name: General Discussion
    url: https://github.com/terryum/book-robot-hand-tactile-sensor/discussions
    about: For general questions and discussions about the book
